#version: '3.8'
# This is a Docker Compose file for setting up a PostGIS database with initial data loading.

services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: wieso
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
